export const descriptions = {
  0: { description: "Bezchmurnie" },
  1: { description: "Przeważnie bezchmurnie" },
  2: { description: "Częściowe zachmurzenie" },
  3: { description: "Pochmurno" },
  45: { description: "Mgła" },
  48: { description: "Osadzanie się mgły szronowej" },
  51: { description: "Mżawka: Lekka" },
  53: { description: "Mżawka: Umiarkowana" },
  55: { description: "Mżawka: Gęsta" },
  56: { description: "Marznąca mżawka: Lekka" },
  57: { description: "Marznąca mżawka: Gęsta" },
  61: { description: "Deszcz: Lekki" },
  63: { description: "Deszcz: Umiarkowany" },
  65: { description: "Deszcz: Gwałtowny" },
  66: { description: "Marznący deszcz: Lekki" },
  67: { description: "Marznący deszcz: Gwałtowny" },
  71: { description: "Opady śniegu: Lekkie" },
  73: { description: "Opady śniegu: Umiarkowane" },
  75: { description: "Opady śniegu: Gwałtowne" },
  77: { description: "Grad" },
  80: { description: "Przelotne opady deszczu: niewielkie" },
  81: { description: "Przelotne opady deszczu: Umiarkowane" },
  82: { description: "Przelotne opady deszczu: Gwałtowne" },
  85: { description: "Przelotne opady śniegu" },
  86: { description: "Przelotne opady śniegu" },
  95: { description: "Burza: Słaba lub umiarkowana" },
  96: { description: "Burza z piorunami" },
  99: { description: "Burza z ciężkim gradem" },
};
